skip-interpreter-query = true
disable-search-path-heuristics = true
site-package-path = ["", ".venv/lib/python3.13/site-packages"]

[build-system]
type = "query-script"
command = "python3"
args = ["tools/pyrefly_bazel_query.py"]