project-excludes=[".venv", "bazel*", ".pytest_cache"]

skip-interpreter-query = true
disable-search-path-heuristics = true
site-package-path = ["", ".venv/lib/python3.12/site-packages/"]

[build-system]
type = "custom"
command = ["./tools/pyrefly_bazel_query.py"]