name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v1

      - name: Run pytest suite
        run: pytest

      - name: Run pyrefly type check
        run: pyrefly check -c pyrefly-ci.toml
